name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        resource-group: skd-aks-demo-rg
        cluster-name: skd-demo-aks

    - name: Build Docker image
      run: |
        docker build -t skddemoacr.azurecr.io/my-static-site:${{ github.sha }} .

    - name: Push Docker image to ACR
      run: |
        docker push skddemoacr.azurecr.io/my-static-site:${{ github.sha }}

    - name: Update AKS deployment
      run: |
        kubectl set image deployment/myapp myapp=skddemoacr.azurecr.io/my-static-site:${{ github.sha }}
